### ISSUE TITLE
厂主好，您能提供一下这个比赛的数据集么？825923287@qq.com,麻烦您了~

### ISSUE THREAD

**Issue by Leef0806** [whut2962575697/image_seg#1]
厂主好，您能提供一下这个比赛的数据集么？825923287@qq.com,麻烦您了~

**Comment by whut2962575697** [comment]
数据集请在https://github.com/whut2962575697/Awesome-Deep-Learning-of-Remote-Sensing上自行下载

**Comment by whut2962575697** [comment]
数据集请在https://github.com/whut2962575697/Awesome-Deep-Learning-of-Remote-Sensing 上自行下载
